add INLINE existing branch check 15

diff --git a/.github/actions/branch-exists-guard/action.yaml b/.github/actions/branch-exists-guard/action.yaml
--- a/.github/actions/branch-exists-guard/action.yaml
+++ b/.github/actions/branch-exists-guard/action.yaml
@@ -17,14 +17,15 @@ runs:
   steps:
     - id: guard
       run: |
-        git show-branch main &>/dev/null && echo yes || echo no
-
-        git ls-remote --exit-code --heads https://github.com/${{ github.repository }} ${{ inputs.branch }}
-        echo "This is the exit code"
-        echo $?
-        BRANCH_EXISTS=$(if [ $? -ne 0 ]; then echo true; else echo false; fi)
-        echo "Branch exists"
-        echo BRANCH_EXISTS
-        echo $BRANCH_EXISTS
+        BRANCH_EXISTS=false
+        git show-branch main &>/dev/null && BRANCH_EXISTS=true || BRANCH_EXISTS=false
+#
+#        git ls-remote --exit-code --heads https://github.com/${{ github.repository }} ${{ inputs.branch }}
+#        echo "This is the exit code"
+#        echo $?
+#        BRANCH_EXISTS=$(if [ $? -ne 0 ]; then echo true; else echo false; fi)
+#        echo "Branch exists"
+#        echo BRANCH_EXISTS
+#        echo $BRANCH_EXISTS
         echo "::set-output name=branch-exists::$(echo $BRANCH_EXISTS)"
       shell: bash
